version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.28.2
    ports:
      - "8081:8080"
      - "50051:50051"
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      CLUSTER_HOSTNAME: 'node1'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
    volumes:
      - weaviate_data:/var/lib/weaviate

  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    environment:
      ENABLE_CUDA: '0'  # Đặt là 1 nếu bạn có GPU

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: meat-scm-chat-bot-server:latest
#    env_file:
#      - .env
#    ports:
#      - "8000:8000"
#    depends_on:
#      - weaviate
#      - t2v-transformers
#    restart: unless-stopped
#    volumes:
#      - ./:/app
#    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --proxy-headers

volumes:
  weaviate_data:
